### ISSUE TITLE
Campo rut en crear cuenta manual debe transformar la K en minusculas

### ISSUE THREAD

**Issue by diegoserranobst** [diegoserranobst/cuentadigital-issues#1]

**Comment by harbsystem** [comment]
No solo en el formulario de cuenta manual si no que tambien cuando se hace importación por la integración

**Comment by diegoserranobst** [comment]
Se agreggó custom function al proceso de creación desde GUI.

**Comment by diegoserranobst** [comment]
Tambien sea gregó la función a buscarut

**Comment by diegoserranobst** [comment]
Se aplicó logica a función uploadCollects.
Esta quedó actualziada inmediatamente.
Las funciones de GUI serán actualziadas en el proximo upgrade
